name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '7.0.x'
  
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Check current directory
      run: |
        echo "Current directory is"
        pwd
        echo "Directory content is"
        ls -a
        
    - name: Check ProjetSport directory
      run: ls -a ProjetSport
      
    - name: Install .NET Workloads
      run: dotnet workload install maui-android

    - name: Install dependencies
      run: dotnet restore ProjetSport/ProjetSport.sln 
      
    - name: Check Keystore File
      run: ls -la ProjetSport/

    - name: Build
      run: dotnet build --configuration Release --no-restore ProjetSport/ProjetSport.sln
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/ProjetSport/my-release-key.keystore
        KEYSTORE_PASSWORD:  ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        

    - name: Publish
      run: dotnet publish ProjetSport/ProjetSport/ProjetSport.csproj --framework net7.0-android --configuration Release --output ./publish/android
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools



    - name: Update firebase.json
      run: |
        echo '{ "hosting": { "public": "./publish/android", "ignore": ["firebase.json", "**/.*", "**/node_modules/**"] } }' > firebase.json


    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: appdistribution:distribute ./publish/android/com.companyname.projetsport-Signed.apk --app 1:284517297402:android:3175896e4b44aa26fced43 --groups testeurs
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON}}
        PROJECT_ID: 1:284517297402:android:3175896e4b44aa26fced43


