name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
  
    - name: Checkout
      uses: actions/checkout@v3 # update to the latest version

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2 # update to the latest version
      
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Run my custom action
      uses: my-org/my-custom-action@v1

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: appdistribution:distribute publish/com.companyname.projetsport-Signed.apk
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        PROJECT_ID: 1:284517297402:android:3175896e4b44aa26fced43

